### ISSUE TITLE
Issues for categorical rasters

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#811] opened 2023-11-10 09:51 UTC
@mtennekes recently, I encounter three issues related to categorial rasters and their color tables (see the code below):

- Issue 1: color table set in **terra** is not used in `tm_raster()`
- Issue 2: when category labels are added -- `tm_raster()` returns an error
- Issue 3: plotting large rasters takes a lot of time and consumes tons of RAM (as compared to `plot()`)

``` r
library(terra)
#> terra 1.7.55
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
library(tmap)
```

## Issue 1

``` r
# issue 1
?coltab
r = rast(ncols=3, nrows=3, vals=1:9)
plot(r) # original raster
```

![](https://i.imgur.com/qJxKk6a.png)

``` r

coltb = data.frame(value=1:9, col=rainbow(9, end=.9))
coltb
#>   value     col
#> 1     1 #FF0000
#> 2     2 #FFAC00
#> 3     3 #A6FF00
#> 4     4 #00FF06
#> 5     5 #00FFB3
#> 6     6 #009FFF
#> 7     7 #0D00FF
#> 8     8 #B900FF
#> 9     9 #FF0099
coltab(r)  =  coltb
plot(r) # raster with color table
```

![](https://i.imgur.com/ob5RiX1.png)

``` r

tm_shape(r) +
  tm_raster()
```

![](https://i.imgur.com/fZc28yR.png)

## Issue 2

``` r

# issue 2
library(osfr)
library(rnaturalearth)
#> Support for Spatial objects (`sp`) will be deprecated in {rnaturalearth} and will be removed in a future release of the package. Please use `sf` objects with {rnaturalearth}. For example: `ne_download(returnclass = 'sf')`

dir.create("data")
osf_retrieve_node("xykzv") |>
        osf_ls_files(n_max = Inf) |>
        osf_download(path = "data",
                     conflicts = "overwrite")
#> # A tibble: 11 × 4
#>    name                        id                       local_path  meta        
#>    <chr>                       <chr>                    <chr>       <list>      
#>  1 landform.tif                5f118a150870f2003c09d264 data/landf… <named list>
#>  2 geomorphons_pol.tif.ovr     5f11830b6ef440003bbcca10 data/geomo… <named list>
#>  3 lf_palette.csv              5f118a0b0870f2004d0972e6 data/lf_pa… <named list>
#>  4 geomorphons_pol.tfw         5f1182e26ef4400034bcd3e9 data/geomo… <named list>
#>  5 lc_am_2018.tif              5f11890b0596f6002e79bbd7 data/lc_am… <named list>
#>  6 lc_palette.csv              5f11890b0870f2003c09d187 data/lc_pa… <named list>
#>  7 suw_lp.gpkg                 5f1182e26ef4400035bce3df data/suw_l… <named list>
#>  8 geomorphons_pol.tif.aux.xml 5f1182e26ef440003bbcc9ab data/geomo… <named list>
#>  9 geomorphons_pol.tif         5f1182ee0870f2003b09b940 data/geomo… <named list>
#> 10 land_cover.tif              5f118a176ef4400049bc93e5 data/land_… <named list>
#> 11 lc_am_1992.tif              5f11890a0596f6002f79c6e2 data/lc_am… <named list>

lc = rast("data/land_cover.tif")
cameroon = ne_countries(country = "Cameroon", returnclass = "sf") |>
  st_transform(crs = st_crs(lc))

lc_cameroon = crop(lc, cameroon, mask = TRUE)

lc_palette_df = read.csv("data/lc_palette.csv")
coltb = lc_palette_df[c("value", "color")]
coltab(lc_cameroon) = coltb
plot(lc_cameroon)  # raster with color table
```

![](https://i.imgur.com/ruFQztZ.png)

``` r

tm_shape(lc_cameroon) +
  tm_raster()
#> SpatRaster object downsampled to 1221 by 820 cells.
```

![](https://i.imgur.com/EjD8rZW.png)

``` r

levels(lc_cameroon) = lc_palette_df[c("value", "label")]
plot(lc_cameroon)
```

![](https://i.imgur.com/NujDUVT.png)

``` r

tm_shape(lc_cameroon) +
  tm_raster()
#> SpatRaster object downsampled to 1221 by 820 cells.
#> Error in rgb(cti$red, cti$green, cti$blue, cti$alpha, maxColorValue = 255): alpha level NA, not in 0:255
```

## Issue 3

``` r
# issue 3
plot(lc)
```

![](https://i.imgur.com/ycL6YWr.png)

``` r

tm_shape(lc) +
  tm_raster()
#> SpatRaster object downsampled to 1040 by 962 cells.
```

![](https://i.imgur.com/h4Tqyql.png)

**Comment by Rapsodia86** [comment] 2023-11-27 18:04
I will add to the issue. I do have a raster with only one value: 
```
class       : SpatRaster 
dimensions  : 902, 1760, 1  (nrow, ncol, nlyr)
resolution  : 500, 500  (x, y)
extent      : -1986126, -1106126, 1312102, 1763102  (xmin, xmax, ymin, ymax)
coord. ref. : Albers_Conic_Equal_Area 
source(s)   : memory
name        : sum 
min value   :   1 
max value   :   1
```
When using regular `plot()` function, I get:
![image](https://github.com/r-tmap/tmap/assets/55965799/15373368-af1b-43e6-9d29-cbb0f78e2e0f)

Using tmap, I get:

```
tm_shape(water_r_cm) +tm_raster()
SpatRaster object downsampled to 716 by 1397 cells.
Error in if (any(na.omit(x) < min(breaks)) && show.warnings) warning("Values have found that are less than the lowest break",  : 
  missing value where TRUE/FALSE needed
```

```
packageVersion("tmap")
[1] ‘3.99.9000’
```

**Comment by mtennekes** [comment] 2024-01-12 07:50
Issue 1 resolved:

```r
tm_shape(r) +
	tm_raster()
```

![image](https://github.com/r-tmap/tmap/assets/2444081/79db08ca-b0b4-48df-8c3a-e99c9a218e75)


```r
tm_shape(r) +
	tm_raster(col.legend = tm_legend_hide())
```

![image](https://github.com/r-tmap/tmap/assets/2444081/7fb3a24a-2028-4406-825d-535eb287be56)


I can imaging that in most use cases, when `coltab` is specified but `cats` is not, the colors should be treaded as a color map rather than a thematic mapping. If so, it would make sense to treat the object as tm_scale_rgb rather than tm_scale_categorical by default. Can you confirm @Nowosad and @rhijmans ?

**Comment by mtennekes** [comment] 2024-01-15 10:46
Issue 2 already resolved with https://github.com/r-tmap/tmap/commit/823b380c3d2d4286e9ab95ecf34f36272b33558c

Issue 3: where can I get the colors for `lc` @Nowosad @rhijmans ? `coltab(lc)` is null.

**Comment by mtennekes** [comment] 2024-01-15 10:48
Thx @Rapsodia86. Can you create a reproducible example from that (or share the data object)?

**Comment by Nowosad** [comment] 2024-01-15 14:33
> I can imaging that in most use cases, when coltab is specified but cats is not, the colors should be treaded as a color map rather than a thematic mapping. If so, it would make sense to treat the object as tm_scale_rgb rather than tm_scale_categorical by default. Can you confirm @Nowosad and @rhijmans ?

I would think so. If the raster data has color table attached -- then, this is how the raster should look like (by default). 

> Issue 2 already resolved with [823b380](https://github.com/r-tmap/tmap/commit/823b380c3d2d4286e9ab95ecf34f36272b33558c)
> 
> Issue 3: where can I get the colors for `lc` @Nowosad @rhijmans ? `coltab(lc)` is null.

Hi @mtennekes -- this example data does not have colors included (I just wanted to let you know that the plotting is of the raster this size seems to be very time/memory consuming). If you want to test categorical plots of such larger data, you can use colors from "Issue 1". Let me know if you have any other questions.

**Comment by Rapsodia86** [comment] 2024-01-16 14:46
> Thx @Rapsodia86. Can you create a reproducible example from that (or share the data object)?

Sure @mtennekes !
[Raster_test_tmap.zip](https://github.com/r-tmap/tmap/files/13951668/Raster_test_tmap.zip)



```
library(terra)
rast_in <- rast("MYDIR/Raster_test_tmap.tif")
rast_in[rast_in==0] <- NA
plot(rast_in)
library(tmap)
tm_shape(rast_in) +tm_raster()
SpatRaster object downsampled to 716 by 1397 cells.
Error in if (any(na.omit(x) < min(breaks)) && show.warnings) warning("Values have found that are less than the lowest break",  : 
  missing value where TRUE/FALSE needed
plot(rast_in)
```
![image](https://github.com/r-tmap/tmap/assets/55965799/6afbe757-2b8b-42c8-81d1-de9c0e53b616)

**Comment by mtennekes** [comment] 2024-01-29 14:02
@Rapsodia86 this issue is fixed now. It requires the latest GH version of cols4all:

```r
remotes::install_github("mtennekes/cols4all")
```

**Comment by Nowosad** [comment] 2024-01-31 08:13
Thanks @mtennekes -- most of the issues are solved. The main remaining one is related to the low performance of large rasters plotting (~20 slower than `plot()`):

``` r
library(terra)
library(tmap)
lc = rast("https://osf.io/download/m92d7")

system.time({plot(lc)})
```

![](https://i.imgur.com/0R9nKSk.png)

    #>    user  system elapsed 
    #>   0.477   0.142   2.896

    system.time({
      print(tm_shape(lc) +
        tm_raster())
    })
    #> SpatRaster object downsampled to 1040 by 962 cells.

![](https://i.imgur.com/HAv0aZX.png)

    #>    user  system elapsed 
    #>  26.798  20.099  50.624

**Comment by mtennekes** [comment] 2024-02-01 11:24
Ok, this is an issue for which I could use help from someone with terra knowledge:

In the S3 function `tmapGetShapeMeta2`, the levels or unique values are computed for each data variable that is used in the plot are computed. See https://github.com/r-tmap/tmap/blob/master/R/tmapGetShapeMeta.R#L75-L97

They are needed because each data variable can be used for create facets (groups), for instance:

```r
World$well_being_rounded = round(World$well_being)
tm_shape(World) + tm_polygons("HPI") + tm_facets(by = "well_being_rounded")
```

In case of raster-objects (stars/terra/...) these are needed before downsampling, because the number of facets determines the amount of downsampling.

The problem is of course that it takes a lot of time to compute the unique values for large spatial objects if these computations have to be done in R in memory (rather than on-disk via a C algorithm).

Hopefully there exist terra tricks to do this (same for stars). Otherwise, we'll have to block this feature, and make faceting more restrictive: faceting by a numeric variable is only allowed if the spatial object is small. Otherwise the user needs to factorize the data first.

**Comment by Nowosad** [comment] 2024-02-03 13:46
Hi @mtennekes, would it be possible just to use `terra::unique?` It is faster than the current solution and takes much less memory:

``` r
library(terra)
library(tmap)
lc = rast("https://osf.io/download/m92d7")

o = list(drop.NA.facets = TRUE, facet.max = 9)

a = bench::mark(
  a1 <- get_fact_levels_na(terra::values(lc, dataframe=TRUE)[[1]], o),
            a2 <- freq(lc),
            a3 <- unique(lc), check = FALSE
  )
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.

a[, 1:5]
#> # A tibble: 3 × 5
#>   expression                                      min median `itr/sec` mem_alloc
#>   <bch:expr>                                    <bch> <bch:>     <dbl> <bch:byt>
#> 1 a1 <- get_fact_levels_na(terra::values(lc, d… 52.4s  52.4s    0.0191    30.2GB
#> 2 a2 <- freq(lc)                                  28s    28s    0.0357    24.6KB
#> 3 a3 <- unique(lc)                              18.3s  18.3s    0.0545    31.5KB
```

**Comment by rhijmans** [comment] 2024-02-04 07:40
If SpatRaster `x` is categorical you can use `levels(x)` to get the unique values. If `x` has numeric (real) values, `unique(x)` might not work very well as there can be very many unique values; unless you set argument "digits" to something else than `NA`. Perhaps "digits=0" makes sense in the context of faceting; or can that be an option?

And a belated confirmation: 

> I can imaging that in most use cases, when coltab is specified but cats is not, the colors should be treated as a color map rather than a thematic mapping

That is correct.

**Comment by mtennekes** [comment] 2024-02-04 20:53
Thanks @rhijmans . Good point about `unique`. In tmap this is regulated via maximum facets. It is the user's own responsibility to round the data for faceting it needed.

Eventually, I took a pragmatic approach: a `spatSample` of 1e5 cells is taken to find the levels and unique values. (Note: I wouldn't use `terra`s levels and `unique` straight away, because in `get_fact_levels_na` not only the levels are determined, but the values are tabulated in order to find possible empty facets. Very fast, but with the (small) risk of missing a category.

**Comment by mtennekes** [comment] 2024-02-07 16:28
All issues mentioned should be fixed. The final issue I just fixed is that no legend is shown in case a color map is defined (coltab) but no categories (cats), unless the user explicitly defines a legend:

```r
# no legend
tm_shape(lc_cameroon) +
	tm_raster("land_cover")

# with a legend
tm_shape(lc_cameroon) +
	tm_raster("land_cover", col.legend = tm_legend())
```

If anything doesn't work, please reopen this issue

**Closed by mtennekes** 2024-02-07 16:28 UTC
