### ISSUE TITLE
tm_grid labels & ticks not matching all grid lines

### ISSUE THREAD

**Issue by Rapsodia86** [r-tmap/tmap#938] opened 2024-09-24 15:38 UTC
I do have a question about the labels & ticks for tm_grid. 
I have created a plot (pasting a part of it, enough to show the issue), but I have one lat grid line that is missing a label and a tick (42.5). From the documentation, I read that `pretty()` is used to create them. Using it, I get:
> pretty(seq(40.9656,43.19134))
[1] 40.5 41.0 41.5 42.0 42.5 43.0

So, does it mean it "takes" the first value, even when it is outside the extent, and so it does not plot the "fifth" label and tick?

See below:
![image](https://github.com/user-attachments/assets/6130d298-13dd-4d0c-b83f-beaf52d29eb6)

I used `tm_grid(n.x=4,n.y=4,lines = TRUE, crs = 4326, labels.cardinal = FALSE,labels.size = 0.5,labels.pos = c("left", "bottom"),lwd=0.75,col="grey75")` to make it. I have also redone it without n.x & n.y but made no difference for lat labels & ticks. 
Thanks!

tmap_3.99.9001 on
R version 4.4.0 (2024-04-24 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

**Comment by mtennekes** [comment] 2024-09-25 18:12
This is probably due to insufficient space. At least, according the current internal calculateions. Could you make this example reproducible, so that I can check where I can improve this? If this can't improved I'll add an argument `force.labels` that always prints the labels no matter if they fit or not.

A workaround, in case this is urgent: you can increase the `inner.margins` a bit to create some room at the top. Add 

```r
tm_layout(inner.margins = c(0.02, 0.02, 0.1, 0.02)) # bottom, left, top, right
```

to your plot.

**Comment by Rapsodia86** [comment] 2024-09-25 19:42
Here are examples of using just reprojected GADM41.
[GADM41_KGZ_2_proj.zip](https://github.com/user-attachments/files/17137630/GADM41_KGZ_2_proj.zip)

```
shp_in <- vect("YOURDIR/gadm41_KGZ_2_proj.shp")
shp_in_small <- subset(shp_in,shp_in$NAME_1 == "Batken")
shp_in_sf <- st_as_sf(shp_in_small)
```
1) without `inner.margins`
```
tm_shape(shp_in_sf) + 
  tm_grid(n.y=2,lines = TRUE, crs = 4326, labels.cardinal = FALSE,labels.size = 0.5,labels.pos = c("left", "bottom"),lwd=0.75,col="grey75")+tm_borders(col="black")+
tm_facets_wrap(by = "NAME_2",ncol=1,nrow=3)
```
![image](https://github.com/user-attachments/assets/b0410c16-1c92-4b2a-b899-419f9b968c59)

2) `inner.margins = c(0.02, 0.02, 0.1, 0.02)`
```
tm_shape(shp_in_sf) + 
  tm_grid(n.y=2,lines = TRUE, crs = 4326, labels.cardinal = FALSE,labels.size = 0.5,labels.pos = c("left", "bottom"),lwd=0.75,col="grey75")+tm_borders(col="black")+
  tm_facets_wrap(by = "NAME_2",ncol=1,nrow=3)+tm_layout(inner.margins = c(0.02, 0.02, 0.1, 0.02))
```
![image](https://github.com/user-attachments/assets/4a404aa5-1103-4a7d-8147-1f2ffea11ab1)

3) `inner.margins = c(0.02, 0.02, 0.2, 0.02)`
```
tm_shape(shp_in_sf) + 
  tm_grid(n.y=2,lines = TRUE, crs = 4326, labels.cardinal = FALSE,labels.size = 0.5,labels.pos = c("left", "bottom"),lwd=0.75,col="grey75")+tm_borders(col="black")+
  tm_facets_wrap(by = "NAME_2",ncol=1,nrow=3)+tm_layout(inner.margins = c(0.02, 0.02, 0.2, 0.02))
```
![image](https://github.com/user-attachments/assets/60d3e87f-5eee-48a3-850c-66d947c16ed4)


Thank you for your time and help:)

**Comment by mtennekes** [comment] 2024-09-26 06:43
Should be fixed, please test.

**Comment by Rapsodia86** [comment] 2024-09-26 11:05
Will explore next week, when get access to my machine! 
Thank you!:)

**Comment by Rapsodia86** [comment] 2024-10-10 21:17
So far everything looks good! I am closing the issue. Thank you very much!👏🙂

**Closed** 2024-10-10 21:17 UTC
