### ISSUE TITLE
tmap4: geocompr

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#694] opened 2023-02-17 10:08 UTC
@mtennekes -- see a list of five problems I found when trying to update the mapping chapter of geocompr to tmap4:

``` r
library(sf)
library(terra)
library(spData)
# remotes::install_github("r-tmap/tmap@v4")
library(tmap)    # for static and interactive maps
#> Warning: no function found corresponding to methods exports from 'raster' for:
#> 'metadata'
nz_elev = rast(system.file("raster/nz_elev.tif", package = "spDataLarge"))
map_nz = tm_shape(nz) + tm_polygons()
```

``` r
# 1. Raster alpha seems broken -----------------------------------------------
# no alpha
map_nz +
  tm_shape(nz_elev) + tm_raster()
```

![](https://i.imgur.com/zGDwdxJ.png)

``` r
# alpha (only in the legend)
map_nz +
  tm_shape(nz_elev) + tm_raster(col_alpha = 0.1)
```

![](https://i.imgur.com/xJr4RET.png)

``` r


# 2. Warning when expression is used --------------------------------------
legend_title = expression("Area (km"^2*")")
# legend_title = "Area (km^2^)"
tm_shape(nz) +
  tm_polygons(fill = "Land_area", fill.legend = tm_legend(title = legend_title))
#> Warning in is.na(l$title): is.na() applied to non-(list or vector) of type
#> 'expression'
```

![](https://i.imgur.com/7QAWlJC.png)

``` r


# 3. tm_scale_bar, tm_compass, tm_title are not exported ------------------
```

``` r
# 4. Raster bbox returns an error -----------------------------------------
nz_region = st_bbox(c(xmin = 1340000, xmax = 1450000,
                      ymin = 5130000, ymax = 5210000),
                    crs = st_crs(nz_height)) |> 
  st_as_sfc()
tm_shape(nz_elev, bbox = nz_region) +
  tm_raster()
#> Error in m[, 1:2, drop = FALSE]: subscript out of bounds
```

``` r
# 5. legend.only does not exist -- how to achieve this in tmap4? ----------
us_states2163 = st_transform(us_states, "EPSG:2163")
us_states2163_dorling = cartogram::cartogram_dorling(us_states2163, "total_pop_15")
tm_shape(us_states2163_dorling) + 
  tm_polygons("total_pop_15",
              fill.scale = tm_scale(values = "BuPu"),
              fill.legend = tm_legend(title = "Total population")) +
  tm_layout(legend.only = TRUE)
#> Error in tm_layout(legend.only = TRUE): unused argument (legend.only = TRUE)
```

**Comment by mtennekes** [comment] 2023-02-17 16:18
1 - 4 done, please check

About 5: how would you want to do this (from a user perspective) ?

The thing is that in v4 there is no (or less) distinction anymore under the hood between legends and other non-spatial 'things' that are drawn op top of the map. Of course I can filter out the non-legends, but there is also a grey area: e.g. legend histograms. The current approach `tm_layout(legend.only = TRUE)` could still be preferable, but there are others, e.g. `tm_hide_map()`

**Comment by Nowosad** [comment] 2023-02-18 09:39
1-4 checked -- they work well.
5. I find the ability to plot the legend only useful (I used it several times in my work). That being said, this does not seem to be something that everyone would use. Thus I think that `tm_layout(legend.only = TRUE)` is fine. Separate functions seem best suited to some standard, often applied, operations.

A new issue:

``` r
library(sf)
library(terra)
library(spData)
# remotes::install_github("r-tmap/tmap@v4")
library(tmap)
nz_elev = rast(system.file("raster/nz_elev.tif", package = "spDataLarge"))
map_nz = tm_shape(nz) + tm_polygons()

# 1. Problem with tm_compass position (and other) ---------------------------
map_nz + 
  tm_compass(type = "8star", position = c("left", "top"))
#> Error in l$position$type: $ operator is invalid for atomic vectors

map_nz + 
  tm_title("NZ") +
  tm_layout(title.position = c("LEFT", "BOTTOM"))
#> Error in l$position$type: $ operator is invalid for atomic vectors
```

**Comment by Nowosad** [comment] 2023-02-18 11:08
@mtennekes There are also two other things I found when playing with the tmap4 examples:

``` r
library(tmap)

# 2. Should it not be unified by default? (tm_legend_combine) ----------------
data(World, metro)
Africa = World[World$continent == "Africa", ]
metro_A = sf::st_intersection(metro, Africa)
#> Warning: attribute variables are assumed to be spatially constant throughout
#> all geometries

tm_shape(Africa) + 
  tm_polygons() +
  tm_shape(metro_A) +
  tm_symbols(fill = "pop1950", size = "pop1950", size.scale = tm_scale(values.scale = 3),
             size.legend = tm_legend_combine("fill"))
#> Error: legends could not be shared; the number of legend items is different

# 3. lwd does not work correctly in the following example -----------------
data(rivers)
tm_shape(rivers) +
  tm_lines(lwd = "scalerank",
           lty = "scalerank")
```

![](https://i.imgur.com/9HMOwYk.png)

**Comment by mtennekes** [comment] 2023-02-18 13:55
1. Yes, that is one of the main changes of v4: the use of `tm_pos_in` and `tm_pos_out` for positions of legends and map components (title, compass, etc). Why this change? Because there are many more options for positioning than in v3. E.g. components can be plot outside of the map. Please let me know if these functions are intuitive to use (and if the docs `tm_pos` are clear). That being said, we could still use `position = c("left", "top")`, which would be a shortcut for `position = tm_pos_in("left", "top")`.

**Comment by mtennekes** [comment] 2023-02-18 14:10
2. Legends can only be combines when the visual variables share the same scale. However, the default scales are different (color => intervals, size => continuous. You can see the default scales:

```r
str(tmap_options("scales.var"))
```

which returns:

```
List of 1
 $ scales.var:List of 11
  ..$ fill      :List of 3
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "intervals"
  .. ..$ int : chr "discrete"
  ..$ col       :List of 3
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "intervals"
  .. ..$ int : chr "discrete"
  ..$ lwd       :List of 3
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "continuous"
  .. ..$ int : chr "discrete"
  ..$ lty       :List of 2
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "categorical"
  ..$ shape     :List of 2
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "categorical"
  ..$ size      :List of 2
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "continuous"
  ..$ fill_alpha:List of 2
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "intervals"
  ..$ col_alpha :List of 2
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "intervals"
  ..$ area      :List of 2
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "continuous"
  ..$ text      :List of 2
  .. ..$ fact: chr "asis"
  .. ..$ num : chr "caterorical"
  ..$ fontface  :List of 2
  .. ..$ fact: chr "categorical"
  .. ..$ num : chr "caterorical"
```

(the first level is visual variable the second level data class)

```r
tm_shape(Africa) + 
  tm_polygons() +
  tm_shape(metro_A) +
  tm_symbols(fill = "pop1950", size = "pop1950",
    fill.scale = tm_scale_intervals(5),
    size.scale = tm_scale_intervals(n = 5, values.scale = 2),
    size.legend = tm_legend_combine("fill"))
```

![image](https://user-images.githubusercontent.com/2444081/219870068-775dc26c-6479-4207-9133-a2937bacc196.png)

We cannot simply add something like `tm_scale_combine("fill")`, because a scale function also relates to the type visual variable (e.g. it configures which visual values (e.g. a specific color) are used). However, there may still be a user friendlier way. It has low priority a.t.m.

**Comment by mtennekes** [comment] 2023-02-18 14:26
3. Interesting example! It was actually not a bug, but an artefact (that has been fixed). 

For the legend symbols of the visual variable `lwd`, the (what I call) neutral values from the other visual variables are collected. If, for instance a sequential color scale is used for `col`, then (by default) the middle color is used for the other legends (if any).

What happend in your example is that the first value of `lty` (a dashed line) is used for the legend symbols of `lwd`. So all items are dashed. The neutral lty value can be changed within the scale of lty.  If we want to stick with the default scale, we can use the general `tm_scale` function (which will pass on argument to the default scale function). 

```r
tm_shape(rivers) +
  tm_lines(lwd = "scalerank",
    lty = "scalerank",
    lty.scale = tm_scale(value.neutral = "solid"))
```

![image](https://user-images.githubusercontent.com/2444081/219870836-56e40703-bdf4-4258-b0a7-632aa1f92822.png)

Since I find this neutral value much more intuitive than a solid line, I have changed the default neutral value for lty (see `tmap_options("value.neutral")`.

**Comment by Nowosad** [comment] 2023-02-18 17:57
Great, thanks @mtennekes. 

I also added a fairly large PR at https://github.com/r-tmap/tmap/pull/695/files, but its goal is just to do some cleaning. 

Now, I will look forward to the `tmap_arrange()` function, and then I will test all of the tmap code in geocompr (not only in the mapping chapter) and report on it.

**Comment by mtennekes** [comment] 2023-02-18 18:46
> 1. ... we could still use `position = c("left", "top")`, which would be a shortcut for `position = tm_pos_in("left", "top")`.

Implemented!

**Comment by mtennekes** [comment] 2023-02-18 18:57
First, I will make sure the current examples also work in view mode. Then I'll continue with `tmap_arrange` and `qtm`.

**Comment by Nowosad** [comment] 2023-02-18 19:03
Sounds like a gook plan.

**Comment by mtennekes** [comment] 2023-03-06 21:05
> Great, thanks @mtennekes.
> 
> I also added a fairly large PR at https://github.com/r-tmap/tmap/pull/695/files, but its goal is just to do some cleaning.
> 
> Now, I will look forward to the `tmap_arrange()` function, and then I will test all of the tmap code in geocompr (not only in the mapping chapter) and report on it.

I've implemented `tmap_arrange`, but only migrated the code and did the minimal to make it work. It will probably crash with knitr (so will other tmap4 maps). Please take a look and let me know if something doesn't work.

Are there any other features for `tmap_arrange` that would be handy?

**Comment by Robinlovelace** [comment] 2023-03-06 21:26
Amazing work Martijn and Jakub, thanks from Leeds!

**Comment by Nowosad** [comment] 2023-03-07 09:46
@mtennekes when I use `tmap_arrange()` the raster downsampling is performed twice per raster data:

``` r
library(terra)
library(tmap) 
tmap_mode("plot")
#> tmap mode set to 'plot'
nz_elev = rast(system.file("raster/nz_elev.tif", package = "spDataLarge"))

# one downsampling
map_nz1 = tm_shape(nz_elev) + tm_raster(col_alpha = 0.7)
map_nz1
#> SpatRaster object downsampled to 1141 by 877 cells.
```

![](https://i.imgur.com/tcu080Y.png)

``` r

# two downsamplings
tmap_arrange(map_nz1)
#> SpatRaster object downsampled to 1141 by 877 cells.
#> SpatRaster object downsampled to 1141 by 877 cells.
```

![](https://i.imgur.com/YLni8Xx.png)

**Comment by Nowosad** [comment] 2023-03-07 10:14
@mtennekes third thing for today: in tmap <4, we could set `title` and `main.title` inside `tm_layout()`. However, in tmap v4, we only have the `tm_title()` function, which works similar to `main.title` by default. What is the expected way of setting `title` in tmap v4?

**Comment by mtennekes** [comment] 2023-03-07 20:29
> @mtennekes I tried to do a quick test of `tmap_arrange()`, but discovered that something is wrong in the current tmap version 4 -- it starts with the view mode by default...

Ah, that was just my laziness, because I was working on legends in view mode. Should indeed by plot by default

**Comment by mtennekes** [comment] 2023-03-07 20:33
> @mtennekes when I use `tmap_arrange()` the raster downsampling is performed twice per raster data (is it expected?):

Yes, that is the downside of the current implementation of `tmap_arrange`. It first produces a print without actual plotting, just to determine the aspect ratio, which is needed to determine the arrangement layout, and the height/width of the image file. If this is specified than (if it works correctly) this step should be bypased.

The second time is the actual plot.

**Comment by mtennekes** [comment] 2023-03-07 20:36
> @mtennekes third thing for today: in tmap <4, we could set `title` and `main.title` inside `tm_layout()`. However, in tmap v4, we only have the `tm_title()` function, which works similar to `main.title` by default. What is the expected way of setting `title` in tmap v4? [I am using `position = tm_pos_in()` currently, but I do not know if that's the suggested approach]

Good question, haven't thought about that. `tm_title` is in principle generic, so it should cover both. Maybe good to have a `tm_main_title` with different defaults? I will check after my holidays (2.5 weeks no tmap development:-)).

**Comment by Nowosad** [comment] 2023-03-08 08:04
@mtennekes 

1. `tmap_arrange()` -- would it be possible to (a) use a much more downscaled data for the aspect ratio calculations (e.g., 100 by 100?) -- it should be faster?; (b) hide the first message?
2. Having `tm_title()` and `tm_main_title()` would be more consistent with tmap v3.
3. Do you have plans to reinstate `tm_ylab()` and `tm_xlab()`?
4. Enjoy the holidays! (And, in the meantime, I will continue my tmap v4 tests).

**Comment by Robinlovelace** [comment] 2023-05-08 14:23
Follow-up on this and just to check: is the intention for v4 to be fully and if not mostly backwards compatible to the extent possible, and for solutions to breaking changes to be attempted? If so it means we need to worry much less about changes to geocompr than if there are lots of breaking changes. This is a continuation of comms in multiple places but thought I'd follow-up here as probably the best place. Also building on https://github.com/r-tmap/tmap/issues/662 where the intention is to minimise breaking changes.

**Comment by mtennekes** [comment] 2023-05-15 08:00
Yes, the intention is indeed to minimise breaking changes.

We should be careful though with the changes within tmap4 that are inherent to the development phase.
For instance, function and argument names.

**Comment by Robinlovelace** [comment] 2023-05-20 21:55
I think writing code that we know will work for every version and flagging issues where `tmap4` fails is a good plan, and kind of what @Nowosad is doing. I do think it would be good to get https://github.com/geocompx/geocompr/pull/953 merged sooner rather than later by setting `eval=FALSE` for failing lines for now... I am starting to think we'll need to submit Geocompr v2 before tmap v4 is complete, which should be fine based on need to minimise breaking changes. We can even say "(syntax may change in **tmap** v4.0.0):" before code chunks that work in the current version but which may fail in the future.

**Closed** 2023-07-31 10:45 UTC
Labels: bug, tmap_v4
